// Test get users
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZDUxODM4N2Q5ODg2YzBmMDc1YjY0YiIsInVzZXJuYW1lIjoicGFrcm96YWtrayIsImlhdCI6MTY3NDkwOTg4MSwiZXhwIjoxNjc0OTA5OTAxfQ.EDK0e2Yty2vRqICTL9h2RBswIrDRK9DBraxAfJv_i8I

###
// Test register
POST http://localhost:5000/users
Content-Type: application/json

{
    "accountSystem": "PakRozakkk@gmail.com",
    "name": "PakRozakkk",
    "username": "PakRozakkk",
    "password": "d1A@jdk!",
    "confPassword": "d1A@jdk!"
}

###
// Test login
POST http://localhost:5000/login
Content-Type: application/json

{
    "accountSystem": "ahmal@gmail.com",
    "password": "Akun@12345"
}

###
// Test get refresh token
GET  http://localhost:5000/token


###
// Test logout
DELETE  http://localhost:5000/logout
