GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "riki",
    "email": "riki@gmail.com",
    "password": "d1A@jdksa",
    "confPassword": "d1A@jdksa"
}